### ISSUE TITLE
multicore?

### ISSUE THREAD

**Issue by street-grease-coder** [fangq/zmat#4]
It doesn't really tax-out all CPU when running, is there a way to increase performance? (matlab, windows server)

**Comment by fangq** [comment]
zmat does not itself implements zipping/unzipping algorithms; instead, it links with established compression libraries, such as libz, lz4 etc and use their APIs to process data. If these libraries are compiled with multi-core support, zmat should happily take it. 

closing as it is rather a wishlist for libz/lz4/lzma

**Comment by street-grease-coder** [comment]
I understand the general idea of zmat being an interface for compression libraries (mostly written in C as far as I understand). I do not understand why lz4 and the commonly available lz4 libraries seem to claim multithreading, but when I use zmat on a windows server with mutliple cores, it barey reaches 10% CPU. Parfor loops with 4 workers do not seem to impact this performance (at least not by multiple factors). 

To understand: you're suggesting to recompile the lz4 library with multithreading support and then make a pull-request, correct? Unfortunately I'm not sure have the technical skills to do that, but at least maybe someone in the future could do this. The library itself, generally, is a gem. Thanks.

**Comment by fangq** [comment]
@street-grease-coder, thanks for explaining, that makes sense to me now.

for lz (libz), zmat uses dynamic linking and links with whatever libz.so that is compiled/installed on your system. so, it is supports multi-core, zmat would.

for lz4, we actually compiles and links with an internal copy of lz4 source code (under src/lz4), the zmat's makefile may not enable the multi-core support for this compressor. 

to get around this, you can disable the internal copy of lz4, and use the liblz4 installed on your system (available for Linux/Mac), which I assume supports multicore, I've done this for the zmat package I uploaded to Debian, see these commands

https://salsa.debian.org/pkg-octave-team/zmat/-/blob/master/debian/rules#L13-23

with these commands, the compiled zmat library/mex file dynamically links with the liblz4.so on your system and uses more optimized settings.

if you know what compilation flag to enable to compile lz4 src code to use multicore, I'd be happy to add it in the Makefile.
